#!/usr/bin/env python3
"""Build the authored bootstrap bundle from audited local evidence. No network."""
import datetime as dt,hashlib,json,platform,sys
from pathlib import Path
R=Path(__file__).parent; P=R.parent.parent
NOW=dt.datetime.now(dt.timezone.utc).isoformat().replace('+00:00','Z')
def read(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def put(name,obj): (R/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2,sort_keys=True)+'\n')
results=read(R/'results.json');protocol=read(R/'frozen_protocol.json')
source_docs=read(P/'data/incoming/research-bootstrap/documents/receipt.json')
source_docs=[{k:v for k,v in x.items() if k!='local_file'} for x in source_docs]
zip_path=P/'data/incoming/research-bootstrap/allswap-fundingrates-2026-09-21.zip'
sources={'schema_version':'1.0','recorded_at':NOW,'method':'Official Codex tools; public web documents, Chrome official Download button; offline Python only. No market API, credentials or trading account data.','archive':{'source_url':'https://www.okx.com/zh-hans/historical-data','original_filename':zip_path.name,'downloaded_at':'2026-09-22T17:51:24.065702Z','displayed_export_time':'2026/09/23 01:50:45','displayed_export_timezone':'NOT_STATED_BY_UI','source_period_label':'2026/09/21 - 2026/09/21','retrieval_ui':'Funding rate / Perpetual / All / Daily / Confirm / Download; BTC text search had no selectable result but All generated a file successfully.','sha256':sha(zip_path),'bytes':zip_path.stat().st_size,'zip_crc':'PASS','member':results['member'],'member_sha256':results['member_sha256'],'member_bytes':results['member_bytes'],'upstream_publication_time':None,'first_observed_available_at':'2026-09-22T17:51:24.065702Z','download_latency_vs_latest_target_event_hours':'33.8567','latency_qualification':'Elapsed retrieval age, not an established publisher service delay.','raw_disclosure':'LOCAL_ONLY','backup_state':'LOCAL_ONLY_NO_REMOTE_RAW_BACKUP','redistribution_permission':'NOT_ESTABLISHED'},'documents':source_docs,'browser_specification_observations':{'url':'https://www.okx.com/zh-hans/trade-market/info/swap','observation_session_start':'2026-09-22T17:49:41Z','recorded_at':NOW,'data_role':'CONTRACT_RULES_NOT_EXECUTABLE_PRICE','selected_market':'永续 / USDT 本位','account_information_accessed':False},'terms_review':{'url':'https://www.okx.com/help/terms-of-service','last_updated':'2026-09-17','sections':['8.1','8.2'],'decision':'No affirmative redistribution grant established; raw downloads, webpage bodies and row-level extracts stay local. Public package contains original analysis, derived aggregate diagnostic observations and source hashes/links, not an upstream mirror.','not_legal_opinion':True}}
put('sources.json',sources)
quantities={'aapl':('1','AAPL','0.01','0.01','25'),'qqq':('1','QQQ','0.01','0.01','50'),'btc':('0.01','BTC','0.01','0.1','100'),'eth':('0.1','ETH','0.01','0.01','100')}
cards=[]
for product,(face,unit,step,tick,maxlev) in quantities.items():
 r=results['products'][product]
 cards.append({'product_id':product,'spec_version':'observed-20260923-v1','enabled':True,'venue':'OKX','instrument_ref':r['instrument_ref'],'contract_kind':'USDT_MARGINED_PERPETUAL','native_code_evidence':['official_download_instrument_name','official_swap_specification_selection'],'settlement_currency':'USDT','contract_face_value':face,'face_value_unit':unit,'contract_multiplier':'1','quantity_step_contracts':step,'minimum_quantity_contracts':step,'price_tick_usdt':tick,'displayed_max_leverage':maxlev,'rule_observation_recorded_at':NOW,'rule_valid_until':None,'reference_underlying':{'ticker':product.upper(),'role':'REFERENCE_NOT_SUBSTITUTE','quote_currency':'USD' if product in ('aapl','qqq') else 'venue-dependent','verified_downloaded_price_data':False},'price_roles':{'target_trade_price':'NOT_DOWNLOADED','mark_price':'RULE_VERIFIED_NO_PATH_DATA','index_price':'RULE_VERIFIED_NO_PATH_DATA','funding_rate':'ACTUAL_SETTLEMENT_SAMPLE_DOWNLOADED'},'funding_sample':r,'funding_schedule':'8-hour spacing observed in sample, not a perpetual current guarantee','fees':{'maker':None,'taker':None,'slippage':None,'exit_cost':None,'fee_source':'https://www.okx.com/fees','actual_fee_tier':'UNKNOWN_NOT_ACCOUNT_ASSESSED'},'calendar':'Target perpetual 24/7; reference exchange calendar separate' if product in ('aapl','qqq') else 'Target perpetual 24/7','raw_format':'zip containing CSV instrument_name,funding_rate,funding_time; timestamp milliseconds UTC','normalized_format':'offline Decimal rates and aware UTC timestamps; no unknown filled with zero','data_source':'https://www.okx.com/historical-data','gaps':['target trade/mark/index paths','actual trading-fee schedule and applicable tier','download date timezone needs further official evidence','source dissemination time unknown','regional/account eligibility not assessed'],'status':'IDENTITY_AND_SMALL_FUNDING_SAMPLE_VERIFIED','readiness':'UNKNOWN','account_eligibility':'NOT_ASSESSED'})
put('product_capability_cards.json',{'schema_version':'1.0','created_at':NOW,'products':cards,'extension_example_only':{'product_id':'intc','enabled':False,'status':'EXAMPLE_NOT_REGISTERED','source_mapping_template':{'venue':'OKX','specification_page':'https://www.okx.com/zh-hans/trade-market/info/swap','native_code':None},'note':'Catalog expansion test only; no production registration or research plan.'}})
seed_rows=[
('A','数据与规则',['aapl','qqq','btc','eth'],'文件日期、目标身份和资金费单位是否支持可重复成本输入？','官方规则与真实小样本对照','REAL_EXECUTED','核对独立日文件的UTC边界及实际延迟','原始文件哈希或官方字段规则变化'),
('B','趋势与进入方式',['btc','eth'],'确认突破是否改善信息而非仅减少暴露？','相同退出、期限与名义暴露的直接进入/收盘确认','WAITING_TARGET_PRICE_DATA','取得合法成交路径、费用后冻结候选，不预选赢家','新增目标交易路径与费用'),
('C','区间与库存',['eth','btc'],'区间往返收入扣除残余库存和退出成本后是否成立？','固定网格/冻结停用规则与持有基线','WAITING_PATH_AND_LEDGER','先做库存守恒与完整权益，不显示只有已实现网格收入','足够细价格路径、单位与费用齐备'),
('D','资金费与拥挤',['btc','eth','qqq','aapl'],'历史资金费方向收入是否足以覆盖价格暴露及来回成本？','反向资金费方向与相同数量期限的相反暴露对照','FORWARD_PROTOCOL_REGISTERED_INCOMPLETE','2026-09-23 00:05 UTC 开始的单次BTC观察按冻结规则待数据','后续合法目标交易/标记与资金费文件'),
('E','事件与会话',['aapl','qqq'],'参考市场休市时指数自身反馈是否使表面价差不可交易？','常规/延长/休市分层，目标成交-标记-参考价格分开','REAL_MECHANISM_REVIEW_EXECUTED','预登记时段/美元兑USDT/价差与费用联立反证','允许来源提供同步价格与事件发布时间'),
('F','共同暴露',['aapl','qqq','btc','eth'],'多产品结果是否只重复共同市场暴露？','同时点、相同币种、匹配波动和方向的简单基准','WAITING_SYNCHRONIZED_DATA','先规定暴露匹配，不把假设资金结果相加','同步目标路径和参考数据'),
('G','边界与切换',['btc','eth'],'事前状态切换是否覆盖切换成本？','始终运行/简单过滤/等待与条件选择','WAITING_BASE_METHOD_RESULT','仅在有基础结果后检验边界，不追最近冠军','基础方法原规则复核或新市场状态证据'),
('H','AI增量与反向对照',['aapl','qqq','btc','eth'],'事前AI事件信息是否增加可检验信号？','简单价格/结构化事件/AI增量/预登记反向','WAITING_PROSPECTIVE_EVENT_OUTPUT','先留存当时输出和信息截止，旧窗口不补问模型','可核实事件发布时间与新模型前向输出'),
('I','独立复现',['btc','eth'],'冻结机制能否在未用于选择的新样本复现？','原方法与新产品/新时期，参数不重新优化','WAITING_FIRST_METHOD_RESULT','ETH只做将来独立复现，INTC保持禁用示例','有方法版本和未曝光新窗口')]
seeds=[]
for code,title,products,question,baseline,status,nextact,restart in seed_rows:
 seeds.append({'discovery_id':'seed-'+code.lower()+'-20260923','seed_code':code,'title':title,'product_refs':products,'question':question,'baseline':baseline,'status':status,'next_action':nextact,'restart_condition':restart,'mechanism_signature':code+'|'+question,'defer_reason':None if status.startswith('REAL') else nextact,'counts_as_completed_economic_research':False,'source_refs':['research-program-v1','funding-data-audit-v1'] if code in ('A','D') else ['research-program-v1','stock-perpetuals'] if code=='E' else ['research-program-v1']})
put('research_seed_registry.json',{'schema_version':'1.0','created_at':NOW,'scope_note':'A-H eight initial categories plus I independent replication; registration does not claim nine executed strategies.','seeds':seeds,'no_fixed_daily_count':True})
# Derived analytic aggregates, not a row-level copy. Reproduction from these only checks public deductions.
facts={'schema_version':'1.0','kind':'AUTHORED_DERIVED_DIAGNOSTIC_FACTS','source_sha256':results['source_sha256'],'source_csv_sha256':results['member_sha256'],'provenance':'Computed by audit_funding.py from local-only official source; not a substitute for raw-data verification.','products':{k:{kk:v for kk,v in v.items() if kk in ['row_count','unique_event_count','duplicate_timestamp_count','positive_count','negative_count','zero_count','sum_rates_diagnostic','sum_basis_points_diagnostic','within_requested_utc_window_count','outside_requested_utc_window_count','observed_intervals_hours']} for k,v in results['products'].items()},'upstream_data_redistributed':False}
put('derived_facts.json',facts)
put('execution_receipt.json',{'schema_version':'1.0','run_id':'run-funding-audit-20260923','attempt_id':'attempt-1','started_at':protocol['frozen_at'],'completed_at':NOW,'actual_execution':'MANUAL_OFFICIAL_APP_BOOTSTRAP','natural_trigger':False,'python_version':sys.version.split()[0],'platform':platform.platform(),'protocol_sha256':sha(R/'frozen_protocol.json'),'code_sha256':sha(R/'audit_funding.py'),'input_sha256':sha(zip_path),'output_sha256':sha(R/'results.json'),'original_protocol_changed':False,'protocol_deviation':'Expected UTC calendar day was not supplied by filename-dated file. Result records mismatch and partial requested-window coverage. No window relabel or backdating.','status':'COMPLETED_WITH_DATA_BOUNDARY_FINDING','economic_result':'NOT_ESTIMATED'})
print(NOW)
