#!/usr/bin/env python3
"""Build/reuse a static shell, project committed records, and publish one repo.

No model or market clients. This program is invoked by the official application.
Research records are never regenerated by a deployment retry.
"""
from __future__ import annotations
import argparse
import fcntl
import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from researchlib import Store, publish_snapshot
from researchlib.common import atomic_write, canonical, digest, now_iso, read_json
from public_guard import check_paths,tracked_paths
from researchlib.snapshot import GENERATOR_VERSION

def command(args, cwd=ROOT):
    return subprocess.check_output(args,cwd=cwd,text=True).strip()

def source_hash():
    paths=[]
    for part in ('researchlib','scripts','web/src','web/public','.agents/skills'):
        paths.extend(p for p in (ROOT/part).rglob('*') if p.is_file() and '__pycache__' not in p.parts)
    paths.extend(ROOT/p for p in ('web/index.html','web/package.json','web/package-lock.json','web/vite.config.ts','web/tsconfig.json','config/readiness_policy.json','AGENTS.md','docs/THIRD_PARTY_NOTICES.md'))
    return digest(canonical({str(p.relative_to(ROOT)):digest(p.read_bytes()) for p in sorted(set(paths)) if p.exists()}))

def shell_hash():
    paths=list((ROOT/'web/src').rglob('*'))+list((ROOT/'web/public').rglob('*'))+[ROOT/'web'/p for p in ('package.json','package-lock.json','vite.config.ts','tsconfig.json','index.html')]+[ROOT/'docs/THIRD_PARTY_NOTICES.md']
    return digest(canonical({str(p.relative_to(ROOT)):digest(p.read_bytes()) for p in sorted(paths) if p.is_file()}))

def build_shell(force=False):
    state=ROOT/'.local/receipts/shell.json'; current=shell_hash()
    prior=read_json(state) if state.exists() else {}
    if not force and prior.get('source_sha256')==current and (ROOT/'site/index.html').exists():return False
    if any((ROOT/'web').glob('.env*')):raise RuntimeError('UNREVIEWED_BUILD_ENVIRONMENT_FILE')
    subprocess.run(['npm','ci'],cwd=ROOT/'web',check=True)
    subprocess.run(['npm','run','build'],cwd=ROOT/'web',check=True)
    dist=ROOT/'web/dist'; site=ROOT/'site'; site.mkdir(exist_ok=True)
    # Preserve historical snapshots. Asset names are content hashes; index switches last.
    for p in sorted(dist.rglob('*')):
        rel=p.relative_to(dist)
        if p.is_file() and rel.parts[0]!='data' and rel.as_posix()!='index.html':
            atomic_write(site/rel,p.read_bytes())
    atomic_write(site/'.nojekyll',b'')
    atomic_write(site/'third-party-notices.txt',(ROOT/'docs/THIRD_PARTY_NOTICES.md').read_bytes())
    atomic_write(site/'index.html',(dist/'index.html').read_bytes())
    atomic_write(state,canonical({'source_sha256':current,'built_at':now_iso()}))
    return True

def publish(args):
    installation=read_json(ROOT/'.local/installation.json')
    approved=installation.get('approved_source_sha256')
    if args.push:
        if source_hash()!=approved:
            raise RuntimeError('PUBLIC_CODE_NOT_APPROVED: independent validation required before release')
        remote=command(['git','remote','get-url','origin'])
        if remote!=installation.get('allowed_remote'):
            raise RuntimeError('PUBLIC_REMOTE_MISMATCH')
        if command(['git','branch','--show-current'])!='main':raise RuntimeError('Publisher requires reviewed main')
    built=build_shell(args.build)
    lock=ROOT/'.local/publisher.lock'
    with lock.open('a+') as stream:
        try:fcntl.flock(stream,fcntl.LOCK_EX|fcntl.LOCK_NB)
        except BlockingIOError:
            print('LOCK_BUSY: publication owner preserved');return
        if args.push and source_hash()!=approved:raise RuntimeError('SOURCE_CHANGED_BEFORE_PROJECTION')
        store=Store(ROOT)
        records,metadata,anomalies=store.load(strict=False)
        fingerprint=digest(canonical({'records':records,'metadata':metadata,'anomalies':anomalies,'generator_version':GENERATOR_VERSION,'approved_implementation':source_hash()}))
        previous_path=ROOT/'.local/receipts/projection.json'
        previous=read_json(previous_path) if previous_path.exists() else {}
        if fingerprint!=previous.get('input_sha256') or not (ROOT/'site/data/latest.json').exists():
            result=publish_snapshot(store,ROOT/'site/data',now_iso())
            atomic_write(previous_path,canonical({'input_sha256':fingerprint,'generated_at':now_iso(),'result':result}))
        pointer=read_json(ROOT/'site/data/latest.json')
        receipt={'schema_version':'1.0','invoked_at':now_iso(),'snapshot_id':pointer['snapshot_id'],'input_sha256':fingerprint,'shell_built':built,'status':'GENERATED_NOT_PUBLISHED','source_sha256':source_hash(),'rejected_bundles':[{'bundle_id':a.get('bundle_id'),'code':a.get('code')} for a in anomalies]}
        if args.push:
            if source_hash()!=approved:raise RuntimeError('SOURCE_CHANGED_BEFORE_COMMIT')
            # Ordinary publisher only stages generated public outputs, never implementation files.
            candidates=[]
            for directory in ('site','records'):
                candidates.extend(str(p.relative_to(ROOT)) for p in (ROOT/directory).rglob('*') if p.is_file() and not p.name.startswith('.publish'))
            bad=check_paths(sorted(set(candidates+tracked_paths())))
            if bad:raise RuntimeError('PUBLIC_GATE_REJECTED: '+repr(bad))
            if candidates:subprocess.run(['git','add','--',*candidates],cwd=ROOT,check=True)
            staged=command(['git','diff','--cached','--name-only']).splitlines()
            if any(Path(p).parts[0] not in {'site','records'} for p in staged):
                raise RuntimeError('UNEXPECTED_STAGED_FILE: publisher cannot commit unrelated work')
            if staged:
                subprocess.run(['git','commit','-m','Publish verified research snapshot '+pointer['snapshot_id'][:12]],cwd=ROOT,check=True)
            if source_hash()!=approved:raise RuntimeError('SOURCE_CHANGED_BEFORE_PUSH')
            if command(['git','remote','get-url','origin'])!=installation.get('allowed_remote'):raise RuntimeError('PUBLIC_REMOTE_CHANGED_BEFORE_PUSH')
            subprocess.run(['git','push','origin','main'],cwd=ROOT,check=True)
            receipt.update(status='PUSHED_AWAITING_PAGES_READBACK',commit=command(['git','rev-parse','HEAD']))
        output=ROOT/'.local/receipts'/('publish-'+receipt['invoked_at'].replace(':','-')+'.json')
        atomic_write(output,canonical(receipt));print(json.dumps(receipt,ensure_ascii=False,indent=2))

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--build',action='store_true');parser.add_argument('--push',action='store_true');parser.add_argument('--source-hash',action='store_true')
    args=parser.parse_args()
    if args.source_hash:print(source_hash())
    else:publish(args)
